name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm Environment
        uses: concertypin/action/pnpm-install@master

      - name: Run tests
        run: pnpm test
